In [2]:
import pandas as pd
iso = pd.read_csv("iso_3.csv", keep_default_na=False, na_values=['?'])

In [3]:
iso

,id,code,Unnamed: 2,alpha-2,alpha-3,nom_fr,nom_gb,Continent
0,0,1,4,AF,AFG,Afghanistan,Afghanistan,AS
1,1,2,8,AL,ALB,Albanie,Albania,EU
2,2,3,10,AQ,ATA,Antarctique,Antarctica,AN
3,3,4,12,DZ,DZA,Algérie,Algeria,AF
4,4,5,16,AS,ASM,Samoa Américaines,American Samoa,OC
...,...,...,...,...,...,...,...,...
235,235,237,876,WF,WLF,Wallis et Futuna,Wallis and Futuna,OC
236,236,238,882,WS,WSM,Samoa,Samoa,OC
237,237,239,887,YE,YEM,Yémen,Yemen,AS
238,238,241,894,ZM,ZMB,Zambie,Zambia,AF
239,239,242,728,SS,SSD,Soudan du Sud,"""South Sudan""",AF

In [4]:
iso['Code_continent'] = iso.Continent

In [5]:
iso

,id,code,Unnamed: 2,alpha-2,alpha-3,nom_fr,nom_gb,Continent,Code_continent
0,0,1,4,AF,AFG,Afghanistan,Afghanistan,AS,AS
1,1,2,8,AL,ALB,Albanie,Albania,EU,EU
2,2,3,10,AQ,ATA,Antarctique,Antarctica,AN,AN
3,3,4,12,DZ,DZA,Algérie,Algeria,AF,AF
4,4,5,16,AS,ASM,Samoa Américaines,American Samoa,OC,OC
...,...,...,...,...,...,...,...,...,...
235,235,237,876,WF,WLF,Wallis et Futuna,Wallis and Futuna,OC,OC
236,236,238,882,WS,WSM,Samoa,Samoa,OC,OC
237,237,239,887,YE,YEM,Yémen,Yemen,AS,AS
238,238,241,894,ZM,ZMB,Zambie,Zambia,AF,AF
239,239,242,728,SS,SSD,Soudan du Sud,"""South Sudan""",AF,AF

In [6]:
iso.Continent.replace('AF', 'Afrique', inplace=True)
iso.Continent.replace('AS', 'Asie', inplace=True)
iso.Continent.replace('EU', 'Europe', inplace=True)
iso.Continent.replace('OC', 'Océanie', inplace=True)
iso.Continent.replace('SA', 'Amerique du sud', inplace=True)
iso.Continent.replace('NA', 'Amerique du Nord', inplace=True)
iso.Continent.replace('AN', 'Antartique', inplace=True)

In [7]:
iso

,id,code,Unnamed: 2,alpha-2,alpha-3,nom_fr,nom_gb,Continent,Code_continent
0,0,1,4,AF,AFG,Afghanistan,Afghanistan,Asie,AS
1,1,2,8,AL,ALB,Albanie,Albania,Europe,EU
2,2,3,10,AQ,ATA,Antarctique,Antarctica,Antartique,AN
3,3,4,12,DZ,DZA,Algérie,Algeria,Afrique,AF
4,4,5,16,AS,ASM,Samoa Américaines,American Samoa,Océanie,OC
...,...,...,...,...,...,...,...,...,...
235,235,237,876,WF,WLF,Wallis et Futuna,Wallis and Futuna,Océanie,OC
236,236,238,882,WS,WSM,Samoa,Samoa,Océanie,OC
237,237,239,887,YE,YEM,Yémen,Yemen,Asie,AS
238,238,241,894,ZM,ZMB,Zambie,Zambia,Afrique,AF
239,239,242,728,SS,SSD,Soudan du Sud,"""South Sudan""",Afrique,AF

In [8]:
iso.to_csv("iso_def.csv")